### PR TITLE
Generate clients from LINE OpenAPI

### LINKED ISSUE #191: Messaging API - August 2020 update
News: https://developers.line.biz/en/news/2020/08/04/messaging-api-update-august-2020/

- [x] [Unsend event has been added](https://developers.line.biz/en/reference/messaging-api/#unsend-event)
- [x] [The audiences property is now optional instead of required for a certain endpoint](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group)
- [ ] [Create audience for uploading user IDs (by file)](https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group-by-file)
- [ ] [Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by file](https://developers.line.biz/en/reference/messaging-api/#update-upload-audience-group-by-file)
- [x] [Video viewing complete event has been added](https://developers.line.biz/en/reference/messaging-api/#video-viewing-complete)

### LINKED ISSUE #232: Support Rich menu aliases Rich menu switch action apis
News: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

### LINKED ISSUE #244: Messaging API Update - November 2021
News: https://developers.line.biz/en/news/2021/11/09/messaging-api-update/

- [ ] [You can now retrieve the text entered by the user in a message sticker](https://developers.line.biz/en/news/2021/11/09/messaging-api-update/#messaging-api-202111-01)
- [x] [You can now retrieve up to 1000 user IDs of friends](https://developers.line.biz/en/news/2021/11/09/messaging-api-update/#messaging-api-202111-02)

### LINKED ISSUE #251: Flex Message Update 3 released
News:
https://developers.line.biz/ja/news/2022/03/11/flex-message-update-3-released/

- [  ] [A video can now be displayed in the hero block](https://developers.line.biz/en/news/2022/03/11/flex-message-update-3-released/#video-component-2022-03-11)
- [  ] [The max width and height of a box component can now be specified](https://developers.line.biz/en/news/2022/03/11/flex-message-update-3-released/#box-component-2022-03-11)
- [  ] [The line spacing in a text component can now be increased](https://developers.line.biz/en/news/2022/03/11/flex-message-update-3-released/#text-component-2022-03-11)

### LINKED ISSUE #252: Webhook redelivery
News
https://developers.line.biz/ja/news/2022/04/19/webhook-redelivery/

### LINKED ISSUE #255: Added "inputOption" property to action object
NEWS:
https://developers.line.biz/en/news/2022/05/13/richmenu-keyboard/

### LINKED ISSUE #282: Get content transcoding status and a preview image
News URL
https://developers.line.biz/en/news/2023/02/14/messaging-api-updated/

- [Endpoint to verify the preparation status of a video or audio for getting](https://developers.line.biz/en/news/2023/02/14/messaging-api-updated/#preparation-status-20230214)
- [Endpoint to get a preview image of an image or video](https://developers.line.biz/en/news/2023/02/14/messaging-api-updated/#preview-20230214)

### LINKED ISSUE #283: @All in the mention property of the webhooks
News URL
[Messaging API now includes @All in the mention property of the webhooks](https://developers.line.biz/en/news/2023/03/08/messaging-api-updated/)

see the [Text](https://developers.line.biz/en/reference/messaging-api/#wh-text) section of [Message event](https://developers.line.biz/en/reference/messaging-api/#message-event)

### LINKED ISSUE #292: Start to implement code generation based on LINE OpenAPI specification
Some features(https://github.com/line/line-bot-sdk-ruby/issues/283, https://github.com/line/line-bot-sdk-ruby/issues/282, https://github.com/line/line-bot-sdk-ruby/issues/255, https://github.com/line/line-bot-sdk-ruby/issues/252, https://github.com/line/line-bot-sdk-ruby/issues/251, https://github.com/line/line-bot-sdk-ruby/issues/244, https://github.com/line/line-bot-sdk-ruby/issues/232, https://github.com/line/line-bot-sdk-ruby/issues/191) have not been implemented yet in the line-bot-sdk-ruby. The repository https://github.com/line/line-openapi publishes API schemas, which we could utilize by using the OpenAPI generator. This would allow SDK users to always access the latest features in the LINE API.

`2.x` version will contain tons of 💣 Breaking Changes 💣.

However, we plan to keep the `1.x` code within `2.x`, as we understand the challenges for SDK users to immediately transition from a `1.x` library to a `2.x` library.

### PR DESCRIPTION
**Pull request by zenizh**
I generated clients according to the definition of [LINE OpenAPI](https://github.com/line/line-openapi) using [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/ruby.md). I also set up the workflow for GitHub Actions and other related tasks.

### Policy of change

This PR uses the OpenAPI Generator to build clients. The OpenAPI Generator generates clients as gems, which means it generates as many gems as there are clients.

On the other hand, we want a single gem, line-bot-api. So we ignore the auto-generated files that we need as a gem with `.gitignore`.

This makes it work as a single gem by reading each client entry point from `lib/line/client.rb`.

I will also add a script called `bin/generate-clients`. This helps to generate clients in the local environment and is also used to generate clients on GitHub Actions.

### Change details

The main files changed in this PR are:

| File | Overview |
| --- | --- |
| bin/generate-clients | Script to generate clients |
| lib/clients | List of generated clients |
| lib/line/client.rb | Load the client list |
| .github/workflows/generate-clients.yml | Generate client on GitHub Actions -> Set up PR |
| spec | Minimal testing to ensure there are no dependency issues |
| src/main/resources/ruby-client/README.mustache | Override the generated client README |
| .gitignore | Define unnecessary files for generated clients |
| Gemfile | Remove unnecessary dependencies |
| README.md | Rewritten for this change |
| line-bot-spi.gemspec | Organizing dependencies |

### How to review

Due to the large number of files in the difference, it is easier to review the PR source branch:
https://github.com/zenizh/line-bot-sdk-ruby/tree/openapi

---

This pull request resolves #292, resolves #283, resolves #282, resolves #255, resolves #252, resolves #251, resolves #244, resolves #232, resolves #191.

### CODE REVIEW

**Comment by zenizh** [comment]
To maintain compatibility with previous versions, I have made the following commit. This allows methods from previous versions to be used without modification, while still displaying the warning message.
https://github.com/line/line-bot-sdk-ruby/pull/296/commits/c8b141cc781cdb0679f51ccf10c54892ef57174c

**Comment by tokuhirom** [comment]
`validate_signature` method should be implemented in the latest version.

**Comment by tokuhirom** [comment]
I guess, generated codes in `lib/clients/webhook` doesn't support deserializing webhook's payload.
`req = LINE::Client::Webhook::CalbackRequest.new(JSON.parse(request_body))` won't parse Hash object to nested object.
I mean, `req` is instance of `LINE::Client::Webhook::CalbackRequest`. But `req.events[0]` is just Hash, not an instance of the `LINE::Client::Webhook::Event`.

It's suprising.

**Comment by tokuhirom** [comment]
https://github.com/zenizh/line-bot-sdk-ruby/blob/openapi/lib/clients/channel-access-token/lib/line_client_channel_access_token/api/channel_access_token_api.rb#L237-L283

is bit strange.

This endpoint has two functionalities: 'Issue from channel ID and channel secret' and 'Issue from JWT assertion.'

For 'Issue from channel ID and channel secret,' you need to make the request with 'grant_type,' 'client_id,' and 'client_secret.'

For 'Issue from JWT assertion,' you need to make the request with 'grant_type,' 'client_assertion_type,' and 'client_assertion.'

The OpenAPI definition specifies that one of these requests is required: [link to the OpenAPI definition](https://github.com/line/line-openapi/blob/cdac9465346ff0fd97ec2435462d15d45450a168/channel-access-token.yml#L18-L48).

However, in this PR, all the required parameters for both patterns are listed, and there are a few issues:

1. It's defined as [String] in the RDoc, which means nil cannot be passed.
2. Due to client-side validation like [here](https://github.com/zenizh/line-bot-sdk-ruby/blob/openapi/lib/clients/channel-access-token/lib/line_client_channel_access_token/api/channel_access_token_api.rb#L259-L262), you are required to provide valid values for parameters even if you are not using them in one of the patterns."

**Comment by zenizh** [comment]
This pull request will be submitted as a new pull request, so it is closed for now.

**Pull request closed without merging**
