### PR TITLE
Support channel access token v2.1

### PR DESCRIPTION
**Pull request by kimoto**
- https://github.com/line/line-bot-sdk-ruby/issues/179

### CODE REVIEW

**Comment by tokuhirom** [comment]
Is there any reason to wait for a merge?

**Comment by kimoto** [comment]
I have not checked it on the actual device.

**Review by toduq — APPROVED** [review]
Thank you for checking! LGTM, again!

**Comment by kimoto** [comment]
(i've checked on actual device)

**Pull request merged**
